name: firstPipe

on: 
  push:
    branches: [main]

jobs:
  estag:
    runs-on: ubuntu-latest

    steps:
      - name: baixar código do rep.
        uses: actions/checkout@v4

      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: instalar dependência
      - run: pip install pytest

      - name: Execultar teste
      - run: pytest 